version: '3.7'

services:
  app:
    build:
      context: .
    volumes:
      - m2:/root/.m2
    networks:
      - app-network
    depends_on:
      - db
    environment:
      - APP_PORT=${APP_PORT}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

  db:
    image: postgres:12
    networks:
      - app-network
    environment:
      - POSTGRES_USER=${DB_USER-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD-postgres}
      - PGDATA=/data/postgres
    volumes:
      - postgres:/data/postgres
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql

  pgadmin:
    container_name: demo_pgadmin
    image: 'dpage/pgadmin4:4.24'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./docker_pgadmin_servers.json:/pgadmin4/servers.json
    ports:
      - '15433:80'
    entrypoint:
      - '/bin/sh'
      - '-c'
      - "/bin/echo 'db:5432:*:postgres:postgres' > /tmp/pgpassfile && chmod 600 /tmp/pgpassfile && /entrypoint.sh"
    networks:
      - app-network
    depends_on:
      - db

volumes:
  m2: {}
  postgres:
  pgadmin:

networks:
  app-network:
    driver: bridge
