# Build Stage for Spring boot application image
FROM maven:3.8.1-jdk-11

WORKDIR /app

COPY src /app/src/
COPY pom.xml /app/
RUN mvn -f /app/pom.xml clean package -DskipTests

CMD ["java", "-jar", "/app/target/todolist-0.0.1-SNAPSHOT.jar"]

