version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.ci
    container_name: todolist_app
    networks:
      - app-network
    depends_on:
      - db
    env_file: .env
    environment:
      - APP_PORT=${APP_PORT}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

  db:
    image: postgres:12
    networks:
      - app-network
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USER-postgres}
      - POSTGRES_PASSWORD=${DB_USER-postgres}
      - PGDATA=/data/postgres
    volumes:
      - postgres:/data/postgres
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql

volumes:
  m2: {}
  postgres:

networks:
  app-network:
    driver: bridge
