version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.ci
    container_name: todolist_app
    networks:
      - app-network
    depends_on:
      - db
    environment:
      - APP_PORT=8080
      - DB_NAME=todolist
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres

  db:
    image: postgres:12
    networks:
      - app-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/data/postgres
    volumes:
      - postgres:/data/postgres
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql

volumes:
  m2: {}
  postgres:

networks:
  app-network:
    driver: bridge
