version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.ci
    container_name: todolist_app
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres:12
    networks:
      - app-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/data/postgres
    volumes:
      - postgres:/data/postgres
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
        
  pgadmin:
    container_name: demo_pgadmin
    image: 'dpage/pgadmin4:4.24'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./docker_pgadmin_servers.json:/pgadmin4/servers.json
    ports:
      - '15433:80'
    entrypoint:
      - '/bin/sh'
      - '-c'
      - "/bin/echo 'postgres:5432:*:postgres:password' > /tmp/pgpassfile && chmod 600 /tmp/pgpassfile && /entrypoint.sh"

networks:
  app-network:
    driver: bridge
