server:
  port: 8080

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      host: db
      port: 27017
      database: todolist
      username: root
      password: root
      authentication-database: admin
