server:
  port: ${env.SERVER_PORT:8080}

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      host: ${env.MONGO_HOST}
      port: ${env.MONGO_PORT}
      database: ${env.MONGO_DATABASE}
      username: ${env.MONGO_USER}
      password: ${env.MONGO_PASSWORD}
      authentication-database: admin
