server:
  port: 8080

spring:
  datasource:
    platform: postgres
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5

    url: jdbc:postgresql://db:5432/todolist
    username: postgres
    password: postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
