server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    platform: postgres
    hikari:
      connectionTimeout: ${CONNECTION_TIMEOUT:20000}
      maximumPoolSize: ${MAXIMUM_POOL_SIZE:5}

    url: jdbc:postgresql://${DB_HOST:db}:${DB_PORT:5432}/${DB_NAME:todolist}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
